### ISSUE TITLE
"_tkinter.TclError: bitmap "./icons/favicon.ico" not defined" in Linux

### ISSUE THREAD

**Issue by jrudolph** [giorgioangel/vesuvius-kintsugi#2]
Not a big issue, I just commented that line out. I quickly tried to research what's going on but I now just assume that ico files are not supported by Tk in Linux.

```
Traceback (most recent call last):
  File "/home/johannes/git/opensource/_2023/vesuvius-kintsugi/kintsugi.py", line 947, in <module>
    editor = VesuviusKintsugi()
  File "/home/johannes/git/opensource/_2023/vesuvius-kintsugi/kintsugi.py", line 51, in __init__
    self.init_ui()
  File "/home/johannes/git/opensource/_2023/vesuvius-kintsugi/kintsugi.py", line 721, in init_ui
    self.root.iconbitmap("./icons/favicon.ico")
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2109, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "./icons/favicon.ico" not defined
```

**Comment by giorgioangel** [comment]
I removed the favicon for the moment. Thanks!
